# Generated by Django 4.0.3 on 2022-03-16 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='image',
        ),
        migrations.AddField(
            model_name='user',
            name='number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
